// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RinhaDasLendas.Infrastructure.Persistence;

#nullable disable

namespace RinhaDasLendas.Infrastructure.Migrations
{
    [DbContext(typeof(RinhaDasLendasDbContext))]
    partial class RinhaDasLendasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuario_tokens", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftEscolha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CapitaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("capitao_id");

                    b.Property<DateTimeOffset>("DataEscolha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_escolha");

                    b.Property<Guid>("DraftSessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_sessao_id");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer")
                        .HasColumnName("sequencia");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("CapitaoId");

                    b.HasIndex("JogadorId");

                    b.HasIndex("DraftSessaoId", "JogadorId")
                        .IsUnique();

                    b.HasIndex("DraftSessaoId", "Sequencia")
                        .IsUnique();

                    b.ToTable("draft_escolhas", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CriterioCapitaes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("criterio_capitaes");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<int>("DuracaoTurnoSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_turno_segundos");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modo");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int>("QuantidadeReservas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_reservas");

                    b.Property<int>("QuantidadeTimes")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_times");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TamanhoEquipe")
                        .HasColumnType("integer")
                        .HasColumnName("tamanho_equipe");

                    b.Property<Guid?>("TurnoAtualCapitaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("turno_atual_capitao_id");

                    b.Property<Guid?>("TurnoAtualTimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("turno_atual_time_id");

                    b.Property<DateTimeOffset?>("TurnoExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turno_expira_em");

                    b.Property<DateTimeOffset?>("TurnoIniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turno_iniciado_em");

                    b.Property<int?>("TurnoSequencia")
                        .HasColumnType("integer")
                        .HasColumnName("turno_sequencia");

                    b.Property<long>("VersaoEstado")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("versao_estado");

                    b.HasKey("Id");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "Modo", "TurnoExpiraEm");

                    b.ToTable("draft_montagens", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemEscolha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CapitaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("capitao_id");

                    b.Property<Guid>("DraftMontagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_montagem_id");

                    b.Property<Guid?>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<DateTimeOffset>("RegistradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_em");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer")
                        .HasColumnName("sequencia");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CapitaoId");

                    b.HasIndex("JogadorId");

                    b.HasIndex("TimeId");

                    b.HasIndex("DraftMontagemId", "Sequencia")
                        .IsUnique();

                    b.ToTable("draft_montagem_escolhas", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Capitao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("capitao");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<Guid>("DraftMontagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_montagem_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("RotaContextual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rota_contextual");

                    b.Property<Guid?>("TimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_id");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("TimeId");

                    b.HasIndex("DraftMontagemId", "JogadorId")
                        .IsUnique();

                    b.ToTable("draft_montagem_participantes", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemTime", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CapitaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("capitao_id");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cor");

                    b.Property<Guid>("DraftMontagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_montagem_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("CapitaoId");

                    b.HasIndex("DraftMontagemId", "Ordem")
                        .IsUnique();

                    b.ToTable("draft_montagem_times", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemSubstituicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DraftMontagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_montagem_id");

                    b.Property<Guid>("JogadorSaiuId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_saiu_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset>("RegistradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_em");

                    b.Property<Guid>("ReservaEntrouId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_entrou_id");

                    b.Property<Guid>("ResponsavelUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_usuario_id");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_id");

                    b.HasKey("Id");

                    b.HasIndex("DraftMontagemId");

                    b.HasIndex("JogadorSaiuId");

                    b.HasIndex("ReservaEntrouId");

                    b.HasIndex("ResponsavelUsuarioId");

                    b.HasIndex("TimeId");

                    b.ToTable("draft_montagem_substituicoes", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Capitao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("capitao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<Guid>("DraftSessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_sessao_id");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<string>("Time")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("DraftSessaoId", "JogadorId")
                        .IsUnique();

                    b.ToTable("draft_participantes", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CapitaoTimeAId")
                        .HasColumnType("uuid")
                        .HasColumnName("capitao_time_a_id");

                    b.Property<Guid>("CapitaoTimeBId")
                        .HasColumnType("uuid")
                        .HasColumnName("capitao_time_b_id");

                    b.Property<string>("CriterioCapitaes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("criterio_capitaes");

                    b.Property<string>("CriterioPrimeiroPick")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("criterio_primeiro_pick");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<string>("ProximoTime")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proximo_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TamanhoTime")
                        .HasColumnType("integer")
                        .HasColumnName("tamanho_time");

                    b.HasKey("Id");

                    b.HasIndex("CapitaoTimeAId");

                    b.HasIndex("CapitaoTimeBId");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("Status");

                    b.ToTable("drafts", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("DeepLolUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deep_lol_url");

                    b.Property<string>("Discord")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("discord");

                    b.Property<string>("Divisao")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("divisao");

                    b.Property<string>("Elo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("elo");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_exibicao");

                    b.Property<string>("NomeReal")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_real");

                    b.Property<string>("OpGgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("op_gg_url");

                    b.Property<string>("RiotId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("riot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("usuario_id IS NOT NULL");

                    b.ToTable("jogadores", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.PreferenciaRota", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<bool>("NaoJogoNemLascando")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("nao_jogo_nem_lascando");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rota");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogadorId", "Rota")
                        .IsUnique();

                    b.ToTable("preferencias_rotas", null, t =>
                        {
                            t.HasCheckConstraint("ck_preferencias_rotas_prioridade", "prioridade >= 1 AND prioridade <= 5");
                        });
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CapitaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("capitao_id");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tag");

                    b.Property<string>("TagNormalizada")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tag_normalizada");

                    b.HasKey("Id");

                    b.HasIndex("CapitaoId");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique()
                        .HasFilter("status = 'Ativo'");

                    b.HasIndex("Status");

                    b.HasIndex("TagNormalizada")
                        .IsUnique()
                        .HasFilter("status = 'Ativo'");

                    b.ToTable("times", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.TimeMembro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("principal");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_id");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("TimeId");

                    b.HasIndex("TimeId", "JogadorId")
                        .IsUnique();

                    b.ToTable("time_membros", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("NivelHierarquico")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_hierarquico");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000001",
                            Name = "SuperAdmin",
                            NivelHierarquico = 500,
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000002",
                            Name = "Admin",
                            NivelHierarquico = 400,
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000003",
                            Name = "Moderador",
                            NivelHierarquico = 300,
                            NormalizedName = "MODERADOR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000004",
                            Name = "Capitão",
                            NivelHierarquico = 200,
                            NormalizedName = "CAPITÃO"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000005",
                            Name = "Jogador",
                            NivelHierarquico = 100,
                            NormalizedName = "JOGADOR"
                        });
                });

            modelBuilder.Entity("RinhaDasLendas.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login_em");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Infrastructure.Identity.AuditoriaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("acao");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UsuarioAlvoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_alvo_id");

                    b.Property<Guid?>("UsuarioExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_executor_id");

                    b.HasKey("Id");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("UsuarioAlvoId");

                    b.HasIndex("UsuarioExecutorId");

                    b.ToTable("auditoria_usuarios", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<string>("IpCriacao")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_criacao");

                    b.Property<string>("IpRevogacao")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_revogacao");

                    b.Property<string>("MotivoRevogacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_revogacao");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPorTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por_token_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgentCriacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent_criacao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("RinhaDasLendas.Infrastructure.Identity.VinculoDiscord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DesvinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("desvinculado_em");

                    b.Property<string>("DiscordAvatarHash")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("discord_avatar_hash");

                    b.Property<string>("DiscordGlobalName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("discord_global_name");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("discord_user_id");

                    b.Property<string>("DiscordUsername")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("discord_username");

                    b.Property<string>("Escopos")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("escopos");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("VinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vinculado_em");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasFilter("desvinculado_em IS NULL");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("desvinculado_em IS NULL");

                    b.ToTable("vinculos_discord", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftEscolha", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "Capitao")
                        .WithMany()
                        .HasForeignKey("CapitaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftSessao", null)
                        .WithMany("Escolhas")
                        .HasForeignKey("DraftSessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capitao");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemEscolha", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "Capitao")
                        .WithMany()
                        .HasForeignKey("CapitaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftMontagem", null)
                        .WithMany("Escolhas")
                        .HasForeignKey("DraftMontagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftMontagemTime", null)
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capitao");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemParticipante", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftMontagem", null)
                        .WithMany("Participantes")
                        .HasForeignKey("DraftMontagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftMontagemTime", null)
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemTime", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", null)
                        .WithMany()
                        .HasForeignKey("CapitaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftMontagem", null)
                        .WithMany("Times")
                        .HasForeignKey("DraftMontagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagemSubstituicao", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftMontagem", null)
                        .WithMany("Substituicoes")
                        .HasForeignKey("DraftMontagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "JogadorSaiu")
                        .WithMany()
                        .HasForeignKey("JogadorSaiuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "ReservaEntrou")
                        .WithMany()
                        .HasForeignKey("ReservaEntrouId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftMontagemTime", null)
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JogadorSaiu");

                    b.Navigation("ReservaEntrou");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftParticipante", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.DraftSessao", null)
                        .WithMany("Participantes")
                        .HasForeignKey("DraftSessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftSessao", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", null)
                        .WithMany()
                        .HasForeignKey("CapitaoTimeAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", null)
                        .WithMany()
                        .HasForeignKey("CapitaoTimeBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.Jogador", b =>
                {
                    b.HasOne("RinhaDasLendas.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.PreferenciaRota", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", null)
                        .WithMany("Preferencias")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.Time", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", null)
                        .WithMany()
                        .HasForeignKey("CapitaoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.TimeMembro", b =>
                {
                    b.HasOne("RinhaDasLendas.Domain.Entities.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RinhaDasLendas.Domain.Entities.Time", null)
                        .WithMany("Membros")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftMontagem", b =>
                {
                    b.Navigation("Escolhas");

                    b.Navigation("Participantes");

                    b.Navigation("Substituicoes");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.DraftSessao", b =>
                {
                    b.Navigation("Escolhas");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.Jogador", b =>
                {
                    b.Navigation("Preferencias");
                });

            modelBuilder.Entity("RinhaDasLendas.Domain.Entities.Time", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
